import A from './sounds/A.mp3';
import B from './sounds/B.mp3';
import C from './sounds/C.mp3';
import D from './sounds/D.mp3';
import E from './sounds/E.mp3';
import F from './sounds/F.mp3';
import G from './sounds/G.mp3';
import H from './sounds/H.mp3';
import I from './sounds/I.mp3';
import J from './sounds/J.mp3';
import K from './sounds/K.mp3';
import L from './sounds/L.mp3';
import M from './sounds/M.mp3';
import N from './sounds/N.mp3';
import O from './sounds/O.mp3';
import P from './sounds/P.mp3';
import Q from './sounds/Q.mp3';
import R from './sounds/R.mp3';
import S from './sounds/S.mp3';
import T from './sounds/T.mp3';
import U from './sounds/U.mp3';
import V from './sounds/V.mp3';
import W from './sounds/W.mp3';
import X from './sounds/X.mp3';
import Y from './sounds/Y.mp3';
import Z from './sounds/Z.mp3';

import one from './sounds/1.mp3';
import two from './sounds/2.mp3';
import three from './sounds/3.mp3';
import four from './sounds/4.mp3';
import five from './sounds/5.mp3';
import six from './sounds/6.mp3';
import seven from './sounds/7.mp3';
import eight from './sounds/8.mp3';
import nine from './sounds/9.mp3';
import zero from './sounds/0.mp3';

var audiofile =[];
audiofile['A']=A;
audiofile['B']=B;
audiofile['C']=C;
audiofile['D']=D;
audiofile['E']=E;
audiofile['F']=F;
audiofile['G']=G;
audiofile['H']=H;
audiofile['I']=I;
audiofile['J']=J;
audiofile['K']=K;
audiofile['L']=L;
audiofile['M']=M;
audiofile['N']=N;
audiofile['O']=O;
audiofile['P']=P;
audiofile['Q']=Q;
audiofile['R']=R;
audiofile['S']=S;
audiofile['T']=T;
audiofile['U']=U;
audiofile['V']=V;
audiofile['W']=W;
audiofile['X']=X;
audiofile['Y']=Y;
audiofile['Z']=Z;
audiofile['1']=one;
audiofile['2']=two;
audiofile['3']=three;
audiofile['4']=four;
audiofile['5']=five;
audiofile['6']=six;
audiofile['7']=seven;
audiofile['8']=eight;
audiofile['9']=nine;
audiofile['0']=zero;

export default audiofile;
